---

postgres:
  replication:
    role: master
    master:   
      num_wal_segments: 32
      clients:
        max_num: '{{groups["database-standby"]|length + 1}}'
        allowed_addresses: 
        - '127.0.0.1/8' 
        - '{{groups["database-standby"]}}'

