---

# Complete nfs.directories.*.export vars with server-side info
nfs:
  directories:
    'share':
      export:
        allowed_clients: '{{groups["all"]}}'
        opts:
          readonly: no
          subtree_check: yes
          sync: yes
          squash: root
      mount:
        opts:
          noauto: ~
    'backups':
      export:
        allowed_clients: '{{groups["all"])}}'
        opts:
          readonly: no
          subtree_check: yes
          sync: yes
          squash: all
          anon_user: backup
          anon_group: backup
      mount:
        opts:
          noauto: ~
