

- hosts: catalog
  remote_user: root

  vars_files:
  - vars.yml
  
  roles:
  - node
  - ckan
  - collectd-node


- hosts: search-engine
  remote_user: root
  
  vars_files:
  - vars.yml
  
  roles:
  - node
  - solr4
  - collectd-node


- hosts: database
  remote_user: root
  
  vars_files:
  - vars.yml
  
  roles:
  - node
  - postgres9
  - collectd-node

- hosts: monitor
  remote_user: root
  
  vars_files:
  - vars.yml
  
  roles:
  - node
  - collectd-server

