
- hosts: 127.0.0.1
  connection: local
  
  #
  # Tasks
  #
  
  tasks:

  - name: Create directory for temporary stuff
    command: mktemp -d
    register: mktemp
    notify:
    - cleanup
  - debug: var=mktemp

  # Solr 

  - name: Determine CKAN-specific schema file for Solr
    set_fact: 
      schema_url: https://api.github.com/repos/{{publicamundi.github_repos['ckan'].name}}/contents/{{publicamundi.solr.schema_path}}?ref={{publicamundi.github_repos['ckan'].branch}}
  - debug: var=schema_url
 
  - name: Download Solr schema file
    shell: wget -q -O '-' '{{schema_url}}'| jq -r '.download_url'| xargs wget -q -O '{{mktemp.stdout}}/schema.xml' 
    
  - name: Copy schema for a single-core setup for Solr v3
    copy: src={{mktemp.stdout}}/schema.xml dest=roles/solr3/files/etc/solr/conf/schema.xml
  
  - file: path=roles/solr4/files/etc/solr/ckan/conf state=directory mode=0775
  - name: Copy schema for a multi-core setup for Solr v4 
    copy: src={{mktemp.stdout}}/schema.xml dest=roles/solr4/files/etc/solr/ckan/conf/schema.xml
  
  #
  # Handlers
  #

  handlers:

  - name: cleanup
    file: path={{mktemp.stdout}} state=absent

    
