---

project:
  repo:
    key_file: id_rsa-repo
    path: PublicaMundi/geodata.gov.gr.git
    host: repo-wps1.dbnet.ece.ntua.gr 
    ssh_host: wps1.dbnet.ece.ntua.gr
    ssh_port: 12722
    remote_name: dblab
    branch_name: prod
  name: geodata.gov.gr

