---

  #
  # Install APT Packages
  #

  - name: Update APT index
    apt: update_cache=yes

  - name: Install Solr on Tomcat
    apt: pkg={{item}} state=latest
    with_items:
    - solr-tomcat
  
  - name: Backup default Tomcat configuration
    command: cp /etc/tomcat6/server.xml /etc/tomcat6/server.xml.orig creates=/etc/tomcat6/server.xml.orig 
  
  - name: Provide Tomcat server configuration
    template: src=etc/tomcat6/server.xml dest=/etc/tomcat6/server.xml
    notify:
      - restart-tomcat
  
  - name: Provide environment for Tomcat service
    template: src=etc/default/tomcat6 dest=/etc/default/tomcat6
    notify:
      - restart-tomcat

  - name: Backup default Solr configuration
    command: cp /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.orig creates=/etc/solr/conf/schema.xml.orig
  
  - name: Provide Solr's schema file
    copy: src=etc/solr/conf/schema.xml dest=/etc/solr/conf/schema.xml
    notify:
      - restart-tomcat
  
  - name: Print Solr's HTTP endpoint
    debug:
      msg: Browse http://{{inventory_hostname}}:{{tomcat6.connector.port}}/solr

