---

# Note: 
# All addresses for internal nodes specified in inventory (ansible_ssh_host) 
# have to belong to the networking.internal_ipv4.network specified below!

networking:
  public_ipv4:
    iface: ~
  internal_ipv4:
    iface: eth1
    network: '10.0.3.0'
    netmask: '255.255.255.0'
    gateway: '10.0.3.2'
  public_ipv6:
    iface: eth0
    prefix: 64
    scope: global

