---

nameservers:
- '83.212.2.77'
- '194.177.210.10'
- '194.177.210.211'

networking:
  if:
    public_ipv4:
      iface: ~
    internal_ipv4:
      iface: eth1
      address: ~
      network: '10.0.3.0'
      netmask: '255.255.255.0'
      gateway: '10.0.3.2'
    public_ipv6:
      iface: eth0
      address: '{{ansible_default_ipv6.address}}'
      prefix: '{{ansible_default_ipv6.prefix}}'
      scope: global
  nat:
    ssh:
      external_host: admin.publicamundi.eu
      external_port: ~

