---

# Configuration for this project/deployment
project:
  repo:
    ssh_host: gitlab.wps1.dbnet.ece.ntua.gr
    ssh_port: 12922
    key_file: id_rsa-repo
    path: PublicaMundi/geodata.gov.gr.git
    fetch:
      host: r-gitlab.wps1.dbnet.ece.ntua.gr
      key_file: id_rsa-publicamundi-deploy
    push:
      host: gitlab.wps1.dbnet.ece.ntua.gr 
      key_file: id_rsa-repo
    remote: dblab
    branch: prod
  name: geodata.gov.gr

# Configuration for PublicaMundi projects
publicamundi:
  # List involved projects
  github_repos:
    ckan:
      name: Publicamundi/ckan
      branch: dev.publicamundi.eu
    ckanext_archiver:
      name: Publicamundi/ckanext-archiver
      branch: dev.publicamundi.eu
    ckanext_datastorer:
      name: Publicamundi/ckanext-datastorer
      branch: dev.publicamundi.eu
    ckanext_publicamundi:
      name: Publicamundi/ckanext-publicamundi
      branch: dev.publicamundi.eu


# Configuration (global) for CKAN application
ckan:
  databases:
    ckan: 
      dbname: ckan
      owner: ckaner
    datastore:
      dbname: ckan_data
      owner: ckan_datastorer
      readonly_user: ckaner
  
  solr:
    # Specify path for schema.xml relative to CKAN repo 
    schema_path: ckan/config/solr/schema.xml

