---

#
# Setup common boilerplate for actual hosts
#
 
 - hosts: internal:!admin
   remote_user: root
  
   roles:
   - role: boilerplate
     when: not canonical_name is defined

#
# Setup NFS server and clients
#

 - hosts: nfs
   remote_user: root

   pre_tasks:
   - debug: var=nfs
   
   roles:
   - nfs-server
   - nfs-client
   
   tasks: ~

 - hosts: internal:!admin:!nfs 
   remote_user: root
  
   pre_tasks:
   - debug: var=nfs
  
   roles:
   - role: nfs-client
     when: not canonical_name is defined

#
# Setup database servers
#
 
 - hosts: database-master:database-standby
   remote_user: root

   pre_tasks:
   - debug: var=postgres

   roles:
   - postgres


#
# Setup Solr
#

 - hosts: solr
   remote_user: root
  
   roles:
   - solr

   tasks:

   - set_fact:
       solr_url: 'http://{{inventory_hostname}}:{{tomcat.connector.port}}/solr/'

#
# Setup CKAN
#

# TODO

 - hosts: ckan
   remote_user: root

   tasks:

   - set_fact:
      solr_host: '{{groups["solr"]| first}}'
  
   - set_fact:
      solr_url: '{{hostvars[solr_host].solr_url}}'


