---

- hosts: external-admin 
  remote_user: root

  roles:
  - boilerplate
  
  tasks:
  
  - set_fact:
      repo: '{{project.repo}}'
      repo_url: 'git@{{project.repo.host}}:{{project.repo.path}}'

  # Create Python virtual environment
  
  - name: Create virtualenv
    shell: /usr/bin/virtualenv /usr/local/pyenv creates=/usr/local/pyenv

  - name: Install newest version of pip
    pip:  name=pip extra_args='--upgrade' virtualenv=/usr/local/pyenv
  
  - name: Install required Python packages
    pip: name={{item}} virtualenv=/usr/local/pyenv
    with_items:
    - 'pudb'
    - 'pep8'
    - 'ipython'
    - 'pytz'
    - 'argparse'
    - 'jinja2'
    - 'netaddr'
    - 'ansible==1.8.4'

  - name: Create a shortcut to activate the environment
    copy:
      mode: 0744
      dest: ~/pyenv.sh
      content: '. /usr/local/pyenv/bin/activate'

  # Create a workspace and clone this repository

  - name: Copy private key needed for repo
    copy: src=files/keys/{{repo.key_file}} dest=~/.ssh/{{repo.key_file}} mode=0600
  
  - name: Create a workspace
    file: path=~/workspace state=directory mode=0755

  - ssh_config:
      name: '{{repo.host}}'
      hostname: '{{repo.ssh_host}}'
      port: '{{repo.ssh_port}}'
      user: 'git'
      identity_file: '~/.ssh/{{repo.key_file}}'
      strict_host_key_checking: 'no'
  
  - name: Checkout project from repo
    command: git clone
      --recursive -b '{{repo.branch_name}}' -o '{{repo.remote_name}}' '{{repo_url}}' '{{project.name}}'
    args:
      chdir: ~/workspace
      creates: '~/workspace/{{project.name}}'
