---

- hosts: external-admin
  remote_user: root

  pre_tasks:
 
  - assert:
      that:
      - networking.if.public_ipv4.iface
      - networking.if.internal_ipv4.address
      - networking.if.internal_ipv4.address == networking.if.internal_ipv4.gateway
 
  roles:
  - network-node
  
  tasks: ~ 

  post_tasks:

  - name: If rebooted, wait for host to be up again
    local_action: wait_for host={{ansible_ssh_host| default(inventory_hostname)}} state=started port=22 delay=8 timeout=300
    when: shutdown_triggered is defined
