---

# 
# Note: (Maybe move this to README)
# 
# This play is intended to be applied before main deployment of applications (play.yml). 
# Has the following objectives:
#  - Disable Debian's network-manager
#  - Configure internal network (10.0.3.x)
#  - Configure (explicitly) public interfaces (IPv6, IPv4 if exists) 
#  - Setup SSH port forwardings from admin to internal hosts
#
# If all the above are satisfied (e.g. networks are already setup manually be the administrator) 
# it can be safely omitted.
#

- hosts: external-admin
  remote_user: root

  tasks:
  
  - debug: var=inventory_hostname

