---

user: false

export_gpg_keys: true

private_keys: []

postgres:
  pgtune: true

  service:
    listen_addresses: 
    - 'localhost'
    - '{{ansible_default_ipv4.address}}'
    port: 5432

  #
  # Define users
  #

  # Note: If allowed addresses is omited, default is 'samehost' 
  users:
  - name: postgres
    allowed_addresses: 
    - samenet
  
  - name: ckaner
    allowed_addresses: 
    - samehost 
    - ckan.publicamundi.localdomain
  
  - name: ckan_datastorer
    allowed_addresses: 
    - samehost 
    - ckan.publicamundi.localdomain
  
  - name: rasdaman
    allowed_addresses:
    - samehost
  
  - name: petascope
    allowed_addresses:
    - samehost
  
  - name: geoserver
    allowed_addresses:
    - samehost 
    - geoserver.publicamundi.localdomain

  - name: collectd
    trusted: true

  #
  # Additional tablespaces to be created
  #

  tablespaces:
  - name: tablespace_1
    path: /var/local/lib/postgresql/tablespace-1
  
  
  #
  # Databases to be created
  #

  databases:

  - name: ckan
    tablespace: tablespace_1
    owner: ckaner
    extensions: [postgis]

  - name: ckan_tests
    tablespace: tablespace_1
    owner: ckaner
    extensions: []
  
  - name: ckan_data
    tablespace: tablespace_1
    owner: ckan_datastorer
    extensions: [postgis]
    readers: [ckaner, geoserver]
  
  - name: ckan_data_tests
    tablespace: tablespace_1
    owner: ckan_datastorer
    extensions: [postgis]
    readers: [ckaner]

  - name: rasdaman
    tablespace: tablespace_1
    owner: rasdaman
    extensions: []

  - name: petascope
    tablespace: tablespace_1
    owner: petascope
    extensions: []


collectd:
  plugins:
    
    processes: ~
    
    df:
      devices:
      - mountpoint: /
      - mountpoint: /var/local/lib/postgresql
    
    postgresql:
      
      databases:
      - name: ckan
        user: collectd

      - name: ckan_data
        user: collectd

