---

  - name: restart-apache2
    service: name=apache2 state=restarted
  
  - name: ask-reboot
    debug:
      msg: ' ** Reboot for changes to take effect ** '

  # TODO  
  - name: restart-paster
    debug:
  
