---

#
# Setup CKAN application
#
 
 - hosts: solr 
   tasks:
   - set_fact:
       solr_server: '{{inventory_hostname}}:{{tomcat.connector.port}}'
   - set_fact:
       solr_url: 'http://{{solr_server}}/solr/'

 
 - hosts: database-master
   tasks:
   - set_fact:
       db_server: '{{inventory_hostname}}:{{postgres.service.port}}'
   - set_fact:
       db_secrets: '{{postgres.secrets_dir}}'

 
 - hosts: ckan
   remote_user: root

   pre_tasks:
   - set_fact:
       db_host: '{{groups["database-master"]| one}}'
       solr_host: '{{groups["solr"]| one}}'
   
   - set_fact:
       db_server: '{{hostvars[db_host].db_server}}'
       db_secrets: '{{hostvars[db_host].db_secrets}}'
       solr_server: '{{hostvars[solr_host].solr_server}}'
    
   - set_fact:
       ckan:
         database:
           url: >
             postgresql://ckaner:{{lookup("password", db_secrets ~ "/users/ckaner")}}@{{db_server}}/ckan
           datastore_write_url: >
             postgresql://ckan_datastorer:{{lookup("password", db_secrets ~ "/users/ckan_datastorer")}}@{{db_server}}/ckan_data
           datastore_read_url: >
             postgresql://ckan_datareader:{{lookup("password", db_secrets ~ "/users/ckan_datareader")}}@{{db_server}}/ckan_data
         
         solr:
           core_url: 'http://{{solr_server}}/solr/ckan'

         config_name: production
         debug: 0

         serve:
           use: 'apache2-mod-wsgi'
           name: '{{inventory_hostname}}'
           name_aliases: 
           - '{{common_name}}'
   
   - set_fact:
       ckanext: {}

   roles:
   - publicamundi
   - celery

   tasks: ~

