---

- hosts: external:!external-admin
  remote_user: root

  pre_tasks: ~
 
  roles:
  - role: network-node
    when: canonical_name is not defined 
  
  tasks: ~ 

  post_tasks:

  - name: If rebooted, wait for host to be up again
    local_action: wait_for host={{ansible_ssh_host| default(inventory_hostname)}} state=drained port=22 delay=8 timeout=300
    when: shutdown_triggered is defined
