---

user: false

private_keys: []

postgres:
  pgtune: true

  service:
    listen_addresses: 
    - 'localhost'
    - '{{ansible_default_ipv4.address}}'
    port: 5432

  #
  # Define users
  #

  # Note: If allowed addresses is omited, default is 'samehost' 
  users:
  - name: postgres
    allowed_addresses: 
    - samenet
  
  - name: '{{ckan.databases.ckan.owner}}'
    allowed_addresses: 
    - samehost 
    - ckan.publicamundi.localdomain
  
  - name: '{{ckan.databases.datastore.owner}}'
    allowed_addresses: 
    - samehost 
    - ckan.publicamundi.localdomain
  
  - name: rasdaman
    allowed_addresses:
    - samehost
  
  - name: petascope
    allowed_addresses:
    - samehost
  
  - name: geoserver
    allowed_addresses:
    - samehost 
    - geoserver.publicamundi.localdomain

  - name: collectd
    trusted: true
  
  credentials: []

  #
  # Additional tablespaces to be created
  #

  tablespaces:
  - name: tablespace_1
    path: /var/local/lib/postgresql/tablespace-1
  
  
  #
  # Databases to be created
  #

  databases:

  - name: '{{ckan.databases.ckan.dbname}}'
    tablespace: tablespace_1
    owner: '{{ckan.databases.ckan.owner}}'
    extensions: [postgis]

  - name: ckan_tests
    tablespace: tablespace_1
    owner: '{{ckan.databases.ckan.owner}}'
    extensions: []
  
  - name: '{{ckan.databases.datastore.dbname}}'
    tablespace: tablespace_1
    owner: '{{ckan.databases.datastore.owner}}'
    extensions: [postgis]
    readers: 
    - '{{ckan.databases.datastore.readonly_user}}' 
    - 'geoserver'
  
  - name: ckan_data_tests
    tablespace: tablespace_1
    owner: '{{ckan.databases.datastore.owner}}'
    extensions: [postgis]
    readers:
    - '{{ckan.databases.datastore.readonly_user}}' 

  - name: rasdaman
    tablespace: tablespace_1
    owner: rasdaman
    extensions: []

  - name: petascope
    tablespace: tablespace_1
    owner: petascope
    extensions: []


collectd:
  plugins:
    
    processes: ~
    
    df:
      devices:
      - mountpoint: /
      - mountpoint: /var/local/lib/postgresql
    
    postgresql:
      
      databases:
      - name: '{{ckan.databases.datastore.dbname}}'
        user: collectd

      - name: '{{ckan.databases.ckan.dbname}}'
        user: collectd

