---

 - name: Reconfigure CKAN; enable selected plugins
   lineinfile:
     dest: '{{ckan.temp_dir}}/conf.d/{{ckan.config_name}}.section-{{app_config_section_num}}.ini'
     regexp: '^ckan.plugins[ ]*='
     line: 'ckan.plugins = {{selected_ckan_plugins| join(" ")}}'
   notify: ['reassemble-ckan-config']  

 - name: Reconfigure CKAN tests; enable selected plugins
   lineinfile:
     dest: '{{ckan.temp_dir}}/conf.d/tests.section-{{app_config_section_num}}.ini'
     regexp: '^ckan.plugins[ ]*='
     line: 'ckan.plugins = {{(ckan.tests.plugins + ckanext.publicamundi.tests.plugins)| join(" ")}}'
   notify: ['reassemble-ckan-tests-config']
