---

publicamundi:
  # List involved Publicamundi projects
  github_repos:
    ckan:
      name: Publicamundi/ckan
      branch: dev.publicamundi.eu
    ckanext_archiver:
      name: Publicamundi/ckanext-archiver
      branch: dev.publicamundi.eu
    ckanext_datastorer:
      name: Publicamundi/ckanext-datastorer
      branch: dev.publicamundi.eu
    ckanext_publicamundi:
      name: Publicamundi/ckanext-publicamundi
      branch: dev.publicamundi.eu
  

ckan:
  databases:
    ckan: 
      dbname: ckan
      owner: ckaner
    datastore:
      dbname: ckan_data
      owner: ckan_datastorer
      readonly_user: ckaner
  
  solr:
    # Specify path for schema.xml relative to CKAN repo 
    schema_path: ckan/config/solr/schema.xml


collectd:
  server: monitor.publicamundi.localdomain
