---

user:
  name: ckaner
  full_name: CKAN user
  email: admin.publicamundi@imis.athena-innovation.gr

private_keys: []

collectd:
  plugins:
    
    processes: ~
    
    df:
      devices:
      - mountpoint: /

