---

# Packages for base system (base-system)
apt:
  use_backports: yes
  package_groups:
    basic:
      name: basic
      packages:
      - sudo
      - vim
      - vim-scripts
      - screen
      - less
      - tree
      - wget
      - curl
      - jq
      - rsync
      - git
      - htop
      - bzip2
    development:
      name: development tools
      select: yes
      packages:
      - build-essential
      - python-dev
      - python-doc
      - python-virtualenv
      - python-setuptools
    network:
      name: network tools
      select: yes
      packages:
      - dnsutils

# Override hostname (cli)
hostname: '{{inventory_hostname_short}}-publicamundi'

# Configuration for generated passwords

password_spec: 'chars=ascii_letters,digits length=9' 

# Preferences for programs and shells (cli)
prefs:
  bash:
    history_size: 9000
    history_file_size: 80000

# Authorized keys (cli)
authorized_keys:
- name: publicamundi
  key_file: id_rsa-publicamundi

# Known private keys (cli)
private_keys:
- name: publicamundi
  key_file: id_rsa-publicamundi

# Configuration for SSH clients (cli)
ssh_config:
- name: '*.publicamundi.localdomain'
  user: 'root'
  strict_host_key_checking: 'ask'
  identity_file: '~/.ssh/id_rsa-publicamundi'
  preferred_authentications: 'publickey'
- name: '*.publicamundi.eu'
  user: 'root'
  strict_host_key_checking: 'ask'
  identity_file: '~/.ssh/id_rsa-publicamundi'
  preferred_authentications: 'publickey'

# Configuration for Git clients (cli)
git_config: 
  user: 
    name: drmalex07
    email: alexakis@imis.athena-innovation.gr
  merge_tool: ~
  diff_tool: ~

# Configuration for swap space (boilerplate)
swap:
  path: 'memory.swap'
  size: '512M' 
