---

networking:
  # Configure kernel-level behavior
  forward_ipv4: no
  forward_ipv6: no
  
  # Configure present interfaces
  if:
    public_ipv4:
      iface: ~
    internal_ipv4:
      iface: eth1
      address: ~
      network: '10.0.3.0'
      netmask: '255.255.255.0'
      gateway: '10.0.3.2'
    public_ipv6:
      iface: eth0
      address: '{{ansible_default_ipv6.address}}'
      prefix: '{{ansible_default_ipv6.prefix}}'
      scope: 'global'
  
  # Configure NAT
  # The following describe DNAT rules for internal hosts. They are intended
  # to be overriden at host/group level.
  nat:
    ssh:
      external_host: admin.publicamundi.eu
      external_port: ~
  
  # Configure iptables-based firewall
  firewall:
    setup: {}

  # Provide DNS nameservers 
  # Note that the following nameservers will only be used for internal-only nodes
  # which are statically configured on networking.if.internal_ipv4 (and so, cannot 
  # acquire their DNS configuration via DHCP).
  dns:
    ipv4:
      nameservers:
      - '194.177.210.10'
      - '194.177.210.211'
    ipv6:
      nameservers:
      - '2001:648:2ffc:201::10'
      - '2001:648:2ffc:100::211'
      - '2001:4860:4860::8888'
      - '2001:4860:4860::8844'
