
- hosts: 127.0.0.1
  connection: local
  
  vars_files:
  - vars.yml
  
  tasks:
  
  - name: Determine CKAN-specific schema file for Solr
    set_fact: 
      schema_url: https://api.github.com/repos/{{github_repos['ckan'].name}}/contents/{{solr.schema_path}}?ref={{github_repos['ckan'].branch}}
   
  - debug: var=schema_url
 
  - name: Download Solr schema file
    shell: wget -q -O '-' '{{schema_url}}'| jq -r '.download_url'| xargs wget -q -O roles/solr3/files/etc/solr/conf/schema.xml
    

    
