---

geoserver:
  # The internal endpoint to the REST API (convention!)
  api_url: 'http://{{groups["geoserver"]| first}}:8081/geoserver'
  
  # The internal endpoint to reload configuration for the cluster (convention!)
  reload_url: 'http://{{groups["geoserver"]| first}}:8000/reload'

  # The public endpoint
  url: 'http://{{common_name}}/geoserver'

  secrets_dir: '{{"files/secrets/groups/geoserver"| realpath}}' 

tomcat:
  secrets_dir: '{{"files/secrets/groups/geoserver/tomcat"| realpath}}'

