---

  #
  # Install APT Packages
  #
  
  - name: Add APT repository for wheezy-backports
    copy: src=etc/apt/sources.list.d/wheezy-backports.list dest=/etc/apt/sources.list.d/wheezy-backports.list mode=0644

  - name: Update APT index
    apt: update_cache=yes

  - name: Install basic APT packages
    apt: pkg={{item}} state=latest
    with_items: '{{apt_packages}}'

  #
  # Setup user profiles and basic directories
  #

  - group: name=testers

  - name: Create a normal user account
    user: name={{user.name}} createhome=yes shell=/bin/bash groups=testers append=yes
    when: '{{user}}'
  
  - name: Create a Bash profile for root
    template: src=etc/root-profile dest=~/.profile mode=0600
  
  - name: Create a Bash profile for normal user
    sudo: yes
    sudo_user: '{{user.name}}'
    template: src=etc/user-profile dest=~/.profile mode=0600
    when: '{{user}}'

  - name: Create a user-local workspace directory
    sudo: yes
    sudo_user: '{{user.name}}'
    file: path=~/workspace state=directory mode=0755
    when: '{{user}}'

  #
  # Configure SSH
  #

  - name: Assign authorized keys for user
    authorized_key: user={{user.name}} key="{{lookup('file', 'etc/ssh/authorized_keys')}}"
    when: '{{user}}'
  
  - name: Configure client SSH for user
    copy: src=etc/ssh/ssh_config dest=~/.ssh/config mode=0640
    sudo: yes
    sudo_user: '{{user.name}}'
    when: '{{user}}'
  
  - name: Copy RSA public keys for user
    copy: src=~/.ssh/{{item.key_file}}.pub dest=~/.ssh/id_rsa-{{item.name}}.pub mode=0644
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: private_keys
    when: '{{user}}'
 
  - name: Copy RSA private keys for user
    copy: src=~/.ssh/{{item.key_file}} dest=~/.ssh/id_rsa-{{item.name}} mode=0600
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: private_keys
    when: '{{user}}'

  #
  # Configure Git client
  #
  
  - name: Configure Git for user
    copy: src=etc/gitconfig dest=~/.gitconfig 
    sudo: yes
    sudo_user: '{{user.name}}'
    when: '{{user}}'

  - name: Provide bash completion for git
    get_url: url={{git_completion_script}} dest=/etc/bash_completion.d/git force=no mode=0644

  #
  # Configure Vim
  #

  - name: Copy vimrc for root
    copy: src=etc/vim/vimrc dest=/root/.vimrc mode=0644
  
  - name: Copy vimrc for user
    copy: src=etc/vim/vimrc dest=~/.vimrc mode=0644
    sudo: yes
    sudo_user: '{{user.name}}'
    when: '{{user}}'
  
  - name: Rsync vim files for root
    synchronize: src=etc/vim/vim/ dest=/root/.vim/ owner=no group=no delete=yes
  
  - name: Rsync vim files for user
    synchronize: src=etc/vim/vim/ dest=/home/{{user.name}}/.vim/ owner=no group=no delete=yes
    when: '{{user}}'

