---

 - include: stop-serve-with-paster.yml
 
 - include: disable-serve-with-paster.yml

 - name: Disable Apache2 vhost
   file:
     state: absent
     force: yes
     path: '/etc/apache2/sites-enabled/ckan-{{ckan_site_id}}'
   notify: ['restart-apache2']

