---
  
 # TODO: Omit already existing users 
 
 - name: Create basic user accounts
   sudo: yes
   sudo_user: ckaner
   shell: >
     . '{{ckan.pyenv_dir}}/bin/activate' 
     && paster user -c '{{ckan.config_file}}' add '{{item.name}}' password='{{item.password}}' email='{{item.email}}'
   args:
     chdir: '{{ckan.pyenv_dir}}/src/ckan'
   with_items: ckan.users

 - name: Upgrade certain users to administrators
   sudo: yes
   sudo_user: ckaner
   shell: >
     . '{{ckan.pyenv_dir}}/bin/activate' 
     && paster sysadmin -c '{{ckan.config_file}}' add '{{item.name}}'
   args:
     chdir: '{{ckan.pyenv_dir}}/src/ckan'
   with_items: ckan.users
   when: item.is_admin| default(false)
   
