---
 
 - name: Add cronjob for paster-celeryd
   cron: 
     name: "paster-celeryd" 
     user: ckaner 
     special_time: reboot 
     state: present
     job: 'screen -dm -S paster-celeryd ~ckaner/scripts/paster-celeryd.sh'
