---
 
 - stat: path={{ckan.pyenv_dir}}/src/ckan
   register: ckan_src_dir

 - name: Install CKAN cloning from Git repo
   sudo: yes
   sudo_user: ckaner
   pip: 
     virtualenv: '{{ckan.pyenv_dir}}'
     name: 'git+{{ckan.source.repo.url}}@{{ckan.source.repo.branch}}#egg=ckan'
     state: present
     extra_args: '-e'
   when: not ckan_src_dir.stat.exists
 
 - name: Set push-URL for CKAN repo
   sudo: yes
   sudo_user: ckaner
   command: git remote set-url --push origin '{{ckan.source.repo.push_url}}'
   args:
     chdir: '{{ckan.pyenv_dir}}/src/ckan'
   when: (not ckan_src_dir.stat.exists) and (ckan.source.repo.push_url| default(false))
 
 # NOTE: If installed and wants updates, check if there are pending updates on our branch
 - name: Update CKAN source tree
   sudo: yes
   sudo_user: ckaner
   git: 
     repo: '{{ckan.source.repo.url}}' 
     remote: origin 
     update: yes
     dest: '{{ckan.pyenv_dir}}/src/ckan'
     version: '{{ckan.source.repo.branch}}'
   when: ckan_src_dir.stat.exists and ckan.source.update

 - name: Install pip requirements for CKAN
   sudo: yes
   sudo_user: ckaner
   pip:
     virtualenv: '{{ckan.pyenv_dir}}'
     requirements: '{{ckan.pyenv_dir}}/src/ckan/requirements.txt'

