---

 - debug: var=ckan
 - debug: var=ckanext

 # Configure APT repos, install required packages
 
 - include: install-apt-packages.yml

 # Create base directories, install Python virtual environment
 
 - include: create-env.yml

 # Install CKAN and requirements 

 - include: install-ckan-and-requirements.yml

 # Configure CKAN

 - include: configure-ckan.yml 

 # Initialize database (create tables from model)

 - include: init-ckan-db.yml

 # Initialize users. 
 
 # NOTE: This step exists mainly to create some administrative accounts, since users
 # will usually be manipulated from either the web interface or from paster commands.
 
 - include: create-ckan-users.yml

 # Serve WSGI application

 - include: serve.yml
