---

 - debug: var=ckan
 - debug: var=ckanext

 # Configure APT repos, install required packages
 
 - include: install-apt-packages.yml
   tags: ['install']

 # Create base directories, install Python virtual environment
 
 - include: create-env.yml
   tags: ['install', 'pyenv']

 # Install CKAN and requirements 

 - include: install-ckan-and-requirements.yml
   tags: ['install']

 # Configure CKAN

 - include: configure-ckan.yml 

 # Initialize database (create tables from model)

 - include: init-ckan-db.yml
   tags: ['init-db']

 # Initialize users. 
 
 # NOTE: This step exists mainly to create some administrative accounts, since users
 # will usually be manipulated from either the web interface or from paster commands.
 
 - include: create-ckan-users.yml

 # Serve WSGI application

 - name: Check if given deploy method is compatible with debug mode
   assert: 
     that: 
     # The debugging middleware is not usable under apache2 (either as proxy or wsgi container)
     - (not ckan.debug) or ckan.serve.use == 'paster'
   tags: ['deploy']

 - include: serve-with-proxy.yml
   when: ckan.serve.use == 'apache2/paster'
   tags: ['deploy']
 
 - include: serve-with-wsgi.yml
   when: ckan.serve.use == 'apache2-mod-wsgi'
   tags: ['deploy']
