---

 - debug: var=ckan
 - debug: var=ckanext

 # Configure APT repos, install required packages
 
 - include: install-apt-packages.yml
   tags: ['install']

 # Create base directories, install Python virtual environment
 
 - include: create-env.yml
   tags: ['install', 'pyenv']

 # Install base CKAN and requirements 

 - include: install-ckan.yml
   tags: ['install']

 # Install CKAN extension: archiver

 - include: install-ckanext-archiver.yml
   when: ckanext.archiver.install
   tags: ['install']
  
 # Install CKAN extension: datastorer

 - include: install-ckanext-datastorer.yml
   when: ckanext.datastorer.install
   tags: ['install']
 
 # Configure CKAN

 - include: configure-ckan.yml 

 # Initialize database (create tables from model)

 - include: init-ckan-db.yml
   tags: ['init-db']

 # Initialize users. 
  
 - include: create-ckan-users.yml

 # Serve WSGI application

 - name: Check if given deploy method is compatible with debug mode
   assert: 
     that: 
     # The debugging middleware is not usable under apache2 (either as proxy or wsgi container)
     - (not ckan.debug) or ckan.serve.use == 'paster'
   tags: ['deploy']

 - include: serve-with-proxy.yml
   when: ckan.serve.use == 'apache2/paster'
   tags: ['deploy']
 
 - include: serve-with-wsgi.yml
   when: ckan.serve.use == 'apache2-mod-wsgi'
   tags: ['deploy']
