---
 
 - include: enable-serve-with-paster.yml

 - include: start-serve-with-paster.yml
 
 - name: Print paster-serve URL for debugging purposes
   debug:
     msg: 'Browse http://{{ckan.serve.hostname}}:{{ckan.serve.paster_opts.port}}'
   when: ckan.serve.paster_opts.listen_address == '0.0.0.0'
