---
 
 - name: Enable Apache2 modules needed for reverse proxying
   apache2_module: state=present name={{item}}
   with_items:
   - 'proxy'
   - 'proxy_balancer'
   - 'proxy_http'
   notify: ['restart-apache2']

 - name: Generate vhost configuration
   template: 
     src: 'etc/apache2/sites-available/proxy-to-paster' 
     dest: '/etc/apache2/sites-available/ckan-{{ckan_site_id}}'
     owner: www-data
     group: www-data
   notify: ['restart-apache2']
 
 - name: Enable vhost
   file:
     state: link
     force: yes
     path: '/etc/apache2/sites-enabled/ckan-{{ckan_site_id}}'
     src: '../sites-available/ckan-{{ckan_site_id}}'
   notify: ['restart-apache2']

 - name: Print URL
   debug:
     msg: 'Browse http://{{ckan.serve.hostname}}{{ckan.serve.url_prefix}}'

 - name: Print paster URL for debugging purposes
   debug:
     msg: 'Browse http://{{ckan.serve.hostname}}:{{ckan.serve.paster_opts.port}}'
   when: ckan.serve.paster_opts.listen_address == '0.0.0.0'
