---

# Define sudo-capable user
user:
   name: geoserver
   full_name: geoserver
   email: admin@publicamundi.eu
   authorized_keys:
   - key_file: id_rsa-publicamundi
   private_keys:
   - key_file: id_rsa-publicamundi
   ssh_config: '{{ssh_config}}'
   pyenv: ~
   git_config: ~ 
   export_gpg_keys: ~

# Configuration for swap space (boilerplate)
swap:
  size: '1G' 
