---

geoserver:

  # A single geoserver host may run multiple server instances sharing the
  # same data directory. The 1st of them will be (by convention) the master
  # instance of this cluster of servers.
  servers:
  - port: 8081
    shutdown_port: 8001
  - port: 8082
    shutdown_port: 8002

